import "../styles/globals.css"
import { AppProps } from "next/dist/shared/lib/router/router"
import Head from "next/head"
import { router } from "next/client"

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
        <meta
          property="og:url"
          content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
        />
        <meta
          property="og:locale"
          content='ru_RU'
        />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
